# Generated by Django 4.1.5 on 2023-02-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandName', models.CharField(max_length=50)),
                ('bandEmail', models.EmailField(max_length=254)),
                ('bandStyle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'band',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='userBand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.band'),
        ),
    ]
